<?xml version='1.0'?>

<robot name="pole" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- gazebo plugin files for sensors -->
  <xacro:include filename="$(find robotic_charger)/urdf/pole.gazebo" />

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="100" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.2" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height" value="1.2" /> <!-- Link 1 -->
  
  <!-- Used for fixing pole to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="pole"/>
  </joint>

  <!-- Base link -->
  <link name='pole'>

    <inertial>
      <mass value="${mass}"/>
      <origin xyz="0 0 ${height/2}" rpy=" 0 0 0"/>
      <inertia
          ixx="${mass / 12.0 * (width*width + height*height)}" ixy="0" ixz="0"
          iyy="${mass / 12.0 * (height*height + width*width)}" iyz="0"
          izz="${mass / 12.0 * (width*width + width*width)}"
      />
    </inertial>

    <collision name='collision'>
      <origin xyz="0 0 ${height/2}" rpy=" 0 0 0"/> 
      <geometry>
        <box size="${width} ${width} ${height}"/>
      </geometry>
    </collision>

    <visual name='pole_visual'>
      <origin xyz="0 0 ${height/2}" rpy=" 0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height}"/>
      </geometry>
    </visual>
    <gazebo reference="pole">
      <material>Gazebo/Orange</material>
    </gazebo>

  </link>

</robot>